name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 129.80.128.21
          username: ubuntu
          key: 
            AAAAB3NzaC1yc2EAAAADAQABAAABAQC8tlvpidUjMI7aiIkcjpUubbHxTIMKiiqu
            1h5k7awTgbkGp0Y19Q7gakp0Wbs33C0e6XlX94qqTiL2sCFqyUmYc/18GeuUdi/Q
            nvkJ1lnBiKpFLiilu7lFfzchjzV3s1yXoNh8C78I1zhX06AO6dFhTORm2traazjn
            pMbPCClnBFHG17BVpY858kzNN+/kVUHCI51QRLuS0jc0cpK7Wba+kxG2c1T2Xi0M
            /4fGEl9XP78ldqVFKVy1Zf24UEH1+Fs7C76OfSN3eoURQ0ipreVDiMsfQM7cse03
            WvpQj7Q4hV30uzVfDwNdoJekW0afx8VHSahg20Yn4xmiWvt7V7/T
            Private-Lines: 14
            AAABADSTL680TdOkeyAqKtzwYmKRgCJEWTvN+49DKyueRbMXkIdogfiVYgQmyMB6
            oVyyNEXo8PwPhKvm4fnNXzoDg0P8iLIS/J2bgb3DFInnlJEFNL7aWcu2rarNgvwQ
            DGrhZxn9X2LL2PirEVDyriSJguJzTCzVq2Rvu+ZZc2QJl5NR1rObFYdImC9LyyB/
            +iohRuWqUimVIFf/XYPBcKzG+Z0gxIq5coA88HpH9jT7votjumxFO+lpqAo5+m9W
            U1v0qS+7jUyD1mzIGOwcIebm1ilqJsDVQScWYyJMyJxXBK7ccQPsvcsjM7rqFTBQ
            piO5kI+sV4edWcGhPbB00g8z7gEAAACBAPr6yWJC9lgjlYlTg1r88jwLN0JjuV3x
            7i56tpeyf4F3RGglIeHKimCeGXnURzT4PkP2jLpmDH8TyUG5H7bO7E+q6leSiqTZ
            xJjKmLvWGk0hx2k0P84AMK18Raj+Pu6vk3adheZOABlS2kufnITjsdDDgcPJf5i1
            jdI2r0UFk2YBAAAAgQDAfLb89tD089RK5E/E8eHazfMRCtp8jL1mQAF523b4Tq8U
            3MkfMMxvQSKo6vy3AWtwg23oSFo4wvXrOMFyS+28sKtow42r362yZR5nhDcQCrNh
            W3x4qGjn1p8UuLxzmUNzZaAGjzYIx/0jXAUywG3rBPFCN1hLFV/zjxu9Puyt0wAA
            AIBATE7GE7tznK7s0Hv1p2++6QoDe7Fxp5cmCOhdJ16oZG1OYqMH/m5adfbnhuVJ
            OrY2QNrGECkCQxA8bL+UDD5Iv4qgaD0kAFInwQUx6aYteS1cg60HrDNTAYi8UtI6
            MWt/npmjUyPrt0tUZAhI64zOPQ8UFdWuD6LKjPRxuwJwuQ==
          script: |
            cd ofertas_bot
            pm2 stop 3
            git pull
            pm2 reload 3